### ISSUE TITLE
no bearer token provided

### ISSUE THREAD

**Issue by debojitkakoti** [weeco/cortex-gateway#2]
I have provided the bearer_token in scrap_configs but still getting no bearer token provided. Here is my prometheus config.
On port 8071 cortex-gateway is running.
```
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
- job_name: 'prometheus'
  bearer_token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.mUhhZNrgCmfEdk2wXmyNjFjOipw-0ks5X7FLfr4QuPY

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

  static_configs:
    - targets: ['localhost:9090']
remote_write:
  - url: http://localhost:8071/api/prom/push
```
